### ISSUE TITLE
Add new &COMB namelist

### ISSUE THREAD

**Issue by sbenkorichi** [rmcdermo/SublimeFDS#12]
If you haven't started on it locally.
I will get it done.

**Comment by rmcdermo** [comment]
Awesome!  Thank you!  I have not looked at it yet.

**Comment by rmcdermo** [comment]
What I try to do is to keep each namelist group as close as possible to what is in the current code.  So, parameters should be moved from REAC or MISC if possible.  Thanks.

**Comment by sbenkorichi** [comment]
Yes,
I will upload the 3 of them to make sure all changes gets done. 
Another good idea I believe in the future is to write a script to do the work for to update them, unless there is a new namelist to be added.
I will send PR when I get it done.
