### ISSUE TITLE
Highlighting for LOSS arrays in HVAC

### ISSUE THREAD

**Issue by bmralph** [rmcdermo/SublimeFDS#2]
`LOSS(1,2)=1` on the `&HVAC` line is not correctly highlighted.

Appears to be caused by the comma between the two numbers in the parentheses.

**Comment by rmcdermo** [comment]
Are you sure you have latest?  Mine seems to be fine.

![screen shot 2016-08-22 at 10 01 17 am](https://cloud.githubusercontent.com/assets/4418497/17857350/707edeb0-684f-11e6-904d-aef847e71136.png)

**Comment by bmralph** [comment]
Perhaps i don't then. I'll update presently and let you know.

**Comment by bmralph** [comment]
Yup updated and works fine now. Sorry!
