### ISSUE TITLE
Update Namelist

### ISSUE THREAD

**Issue by sbenkorichi** [rmcdermo/SublimeFDS#5]
Randy,
Can you please upload the namelist of the sublime syntax when you have the time.

**Comment by rmcdermo** [comment]
Not sure what you mean.  I keep the sublime namelists up to date as I run into (look at) cases myself.  I would not be surprised if WIND, etc. need updating.  Can you add these (alphabetical order) and send me a PULL REQUEST?

**Comment by sbenkorichi** [comment]
Yes, it's related to Wind, and GLMAT. Also, I noted this happen for Evacuation.
Let's see if we can include them. I will send a PR when I get a chance to work on it.

**Comment by rmcdermo** [comment]
What I did when I started this was to just go through read.f90 and look at the READ_<NAMELIST> routines and make sure they are all accounted for.  Probably need to do this again, as you said, focussing on WIND and PRES.

**Comment by sbenkorichi** [comment]
I'm going to add Evacuation namelist to my local repo. Let me know if you are interested to receive PR for it.

**Comment by rmcdermo** [comment]
If it is an FDS namelist, then yes, else no.

**Comment by sbenkorichi** [comment]
Of course, it's FDS, just gonna grep it from the read as the other namelists, 
Will send PR when I add it up.

**Comment by sbenkorichi** [comment]
Randy,
they're in evac. However, I was checking, Timo, doesn't set them in alphabetic order, does it have to be set in alphabetic order?

**Comment by rmcdermo** [comment]
No, whatever is easiest.

**Comment by sbenkorichi** [comment]
Thanks man, otherwise it would be pain in the butt lol
