### ISSUE TITLE
Commenting doesn't work

### ISSUE THREAD

**Issue by sbenkorichi** [rmcdermo/SublimeFDS#7]
Randy,
When I select single/couple of lines and comment them, it doesn't work. How do you get over this?
If it's not added as a function, then we should see a way how to fix it.

**Comment by rmcdermo** [comment]
I am not sure what you mean.  This works fine for me.

![screen shot 2017-11-04 at 4 58 59 pm](https://user-images.githubusercontent.com/4418497/32409401-8b13207e-c181-11e7-9dbd-59c59f624d7f.png)

Can you be more explicit about what is wrong?

**Comment by sbenkorichi** [comment]
hmm,
On my machine, when I do comment after I highlight certain lines, -->edit --> comment, it doesn't work.
I'm on my laptop now and it's working. This is weird. It does comment for matlab and other file extensions.
I need to check why it's behaving that way.

**Comment by sbenkorichi** [comment]
Solved,
I found that the comments file wasn't included in the appropriate directory. 
Closing
