### ISSUE TITLE
Fully test material layers

### ISSUE THREAD

**Issue by rmcdermo** [rmcdermo/SublimeFDS#9]
@sbenkorichi 

When you have time, can you have a look at MATL line inputs to make sure the array syntax highlights as you expect?  I don't use this often so I am not sure it is right.

**Comment by sbenkorichi** [comment]
Ok

**Comment by rmcdermo** [comment]
Salah,
I did not realize that collaborators on a personal repo are granted push access to the repo.  For now, please let me merge PRs, though.  Thanks!

**Comment by sbenkorichi** [comment]
Feel free to close if the PR does the job. If not, then let me know.
